name: Wiki submodule update
on: 
    gollum
jobs: 
  sync:
    name: 'Wiki submodule sync'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/feature/wiki'
    steps:
        - name: Checkout 
          uses: actions/checkout@v2
        - name: Submodule update
          run: | 
            git submodule update --init --recursive
            git submodule update --remote --recursive
            git config user.email "actions@github.com"
            git config user.name "Github Actions - update submodule"
            git add --all
            git commit -m "Updated wiki submodule"
            git push